








start_frame 3300



start_frame 630	# for sequence 07

start_frame 1879

start_frame 479

start_frame 351

start_frame 342

start_frame 316

start_frame 5

b_process_all_frames 0		# whether to process all frames or only key frames
keyframe_sampling_distance 1


######### IncreMap ##########
Rebuild_map_path /path/to/rebuild_map
Rebuild_map_path /path/to/rebuild_map
Rebuild_map_path /path/to/rebuild_map
EFFECTIVE_LINE_NUM 128
EFFECTIVE_R 150
mapping_step 4


roi_range 40
roi_range 50
roi_range 50

b_debug_mode 0
b_enable_visualization 0


map_resolution 0.2


map_cols 320
map_cols 500

############# bgk params ###############

k_prediction_kernel_radius 2
k_valid_points_num_thresh 3
k_bf_height_std 0.1


k_prediction_kernel_radius_s 0.2
k_prediction_kernel_radius_s 0.71
k_valid_points_num_thresh_s 3

slope_angle_thresh 15


############# range_image_stack params ###############

stack_length 5
spatial_sampling_distance 2.0





############### rolling block map ########################
b_save_to_disk 1
b_load_from_disk 1
b_delete_existing_map 1
small_map_rows 200
big_map_rows 1200

Mode 1
chech_mode 2
    
only_forward_flag 0

RONI_min_x -2

RONI_max_x 2

RONI_min_y -4

RONI_max_y 2.5

RONI_min_z -1.3

RONI_max_z 1


filter_size_map_min 0.4
    
k_initial_seed_search_radius 7.0
    
dynamic_box 60
